host:
  id: montreal-01
  ssh: montreal-01
  domain: storage.evanovation.com
  data_root: /home/ubuntu/databases
  images:
    postgres: postgres:16
    pgbouncer: edoburu/pgbouncer:v1.25.1-p0
    redis: redis:7.2.5
    dragonfly: docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1
    http: hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150
    traefik: traefik:v3.7.8
  backup:
    repos:
      postgres: rclone:onedrive-evanovation:montreal-01/databases/postgres
      kv: rclone:onedrive-evanovation:montreal-01/databases/kv
  one_password:
    vault: Evanovation
    system_item: evanovation-db

databases:
  - name: api-test-01
    type: postgres

  - name: code-share-prod-01
    type: postgres

  - name: cs-ai-prod-01
    type: postgres

  - name: dialogue-dev-01
    type: postgres
    pooler: false

  - name: gpt-accounts-manager-prod-01
    type: postgres

  - name: gpt-share-prod-01
    type: postgres
    max_clients: 2000
    pool_size: 30
    reserve_size: 10

  - name: gpt-share-prod-02
    type: postgres

  - name: gpt-share-prod-03
    type: postgres

  - name: test-dev-01
    type: postgres

  - name: umami-prod-01
    type: postgres

  - name: vercount-prod-01
    type: postgres

  - name: waline-prod-01
    type: postgres

  - name: waline-prod-02
    type: postgres

  - name: whereto-prod-01
    type: postgres

  - name: code-share-prod-01
    type: dragonfly
    memory: 1024mb
    threads: 4

  - name: gpt-share-dev-01
    type: dragonfly

  - name: gpt-share-prod-01
    type: dragonfly
    memory: 1024mb
    threads: 4

  - name: oai-co-prod-01
    type: redis

  - name: oai-co-prod-02
    type: redis

  - name: portfolio-prod-01
    type: dragonfly

  - name: redefine-version-prod-01
    type: dragonfly

  - name: stock-selector-prod-01
    type: redis

  - name: test-dev-01
    type: dragonfly

  - name: vercount-prod-01
    type: dragonfly
    memory: 2048mb
    threads: 4

  - name: xai-server-prod-01
    type: redis
