instances:
  - id: code-share-prod-01
    env: prod
    engine: dragonfly
    container: code-share-prod-01-redis-1
    project: code-share-prod-01
    data: /home/ubuntu/databases/kv/code-share-prod-01/data
    domain: code-share-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/code-share-prod-01/data, compose: /home/ubuntu/databases/kv/code-share-prod-01/docker-compose.yaml, http_domain: code-share-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/code-share-prod-01/data}
    backup: {enabled: true}
    resources: &kv_resources {database: unlimited, http: unlimited}
    secrets: {password: "op://Evanovation/code-share-prod-01-kv/password"}
    settings: {threads: 4, maxmemory: 1024mb, cache: false}
    http: {enabled: true, port: 13390, domain: code-share-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/code-share-prod-01-kv/http-token", max_connections: 20}

  - id: gpt-share-dev-01
    env: dev
    engine: dragonfly
    container: gpt-share-dev-01-redis-1
    project: gpt-share-dev-01
    data: /home/ubuntu/databases/kv/gpt-share-dev-01/data
    domain: gpt-share-dev-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/gpt-share-dev-01/data, compose: /home/ubuntu/databases/kv/gpt-share-dev-01/docker-compose.yaml, http_domain: gpt-share-dev-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/gpt-share-dev-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/gpt-share-dev-01-kv/password"}
    settings: {threads: 1, maxmemory: 256mb, cache: false}
    http: {enabled: true, port: 13389, domain: gpt-share-dev-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/gpt-share-dev-01-kv/http-token", max_connections: 20}

  - id: gpt-share-prod-01
    env: prod
    engine: dragonfly
    container: gpt-share-prod-01-redis-1
    project: gpt-share-prod-01
    data: /home/ubuntu/databases/kv/gpt-share-prod-01/data
    domain: gpt-share-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/gpt-share-prod-01/data, compose: /home/ubuntu/databases/kv/gpt-share-prod-01/docker-compose.yaml, http_domain: gpt-share-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/gpt-share-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/gpt-share-prod-01-kv/password"}
    settings: {threads: 4, maxmemory: 1024mb, cache: false}
    http: {enabled: true, port: 13385, domain: gpt-share-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/gpt-share-prod-01-kv/http-token", max_connections: 20}

  - id: oai-co-prod-01
    env: prod
    engine: redis
    container: oai-co-prod-01-redis-1
    project: oai-co-prod-01
    data: /home/ubuntu/databases/kv/oai-co-prod-01/data
    domain: oai-co-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: redis, image: "redis:latest", image_id: "sha256:e48e4ac2fa6b1dc2bb9abc9278df84653d3b38d5db82a2d414d3814f296e388e", data: /home/ubuntu/databases/kv/oai-co-prod-01/data, compose: /home/ubuntu/databases/kv/oai-co-prod-01/docker-compose.yaml, http_domain: oai-co-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: redis, image: "redis:7.2.5@sha256:f5ef9e24a9ef3b7cc552ae0cbc3cbade4f2877502683496c5d775605ae071412", data: /home/ubuntu/databases/kv/oai-co-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/oai-co-prod-01-kv/password"}
    settings: {}
    http: {enabled: true, port: 13382, domain: oai-co-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/oai-co-prod-01-kv/http-token", max_connections: 20}

  - id: oai-co-prod-02
    env: prod
    engine: redis
    container: oai-co-prod-02-redis-1
    project: oai-co-prod-02
    data: /home/ubuntu/databases/kv/oai-co-prod-02/data
    domain: oai-co-prod-02.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: redis, image: "redis:latest", image_id: "sha256:e48e4ac2fa6b1dc2bb9abc9278df84653d3b38d5db82a2d414d3814f296e388e", data: /home/ubuntu/databases/kv/oai-co-prod-02/data, compose: /home/ubuntu/databases/kv/oai-co-prod-02/docker-compose.yaml, http_domain: null}
    target: {engine: redis, image: "redis:7.2.5@sha256:f5ef9e24a9ef3b7cc552ae0cbc3cbade4f2877502683496c5d775605ae071412", data: /home/ubuntu/databases/kv/oai-co-prod-02/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/oai-co-prod-02-kv/password"}
    settings: {}
    http: {enabled: true, port: 13383, domain: oai-co-prod-02.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/oai-co-prod-02-kv/http-token", max_connections: 20}

  - id: portfolio-prod-01
    env: prod
    engine: dragonfly
    container: portfolio-prod-01-redis-1
    project: portfolio-prod-01
    data: /home/ubuntu/databases/kv/portfolio-prod-01/data
    domain: portfolio-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/portfolio-prod-01/data, compose: /home/ubuntu/databases/kv/portfolio-prod-01/docker-compose.yaml, http_domain: portfolio-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/portfolio-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/portfolio-prod-01-kv/password"}
    settings: {threads: 1, maxmemory: 256mb, cache: false}
    http: {enabled: true, port: 13388, domain: portfolio-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/portfolio-prod-01-kv/http-token", max_connections: 20}

  - id: redefine-version-prod-01
    env: prod
    engine: dragonfly
    container: redefine-version-prod-01-redis-1
    project: redefine-version-prod-01
    data: /home/ubuntu/databases/kv/redefine-version-prod-01/data
    domain: redefine-version-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/redefine-version-prod-01/data, compose: /home/ubuntu/databases/kv/redefine-version-prod-01/docker-compose.yaml, http_domain: redefine-version-prod-01.kv-na01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/redefine-version-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/redefine-version-prod-01-kv/password"}
    settings: {threads: 1, maxmemory: 256mb, cache: false}
    http: {enabled: true, port: 13380, domain: redefine-version-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/redefine-version-prod-01-kv/http-token", max_connections: 20}

  - id: stock-selector-prod-01
    env: prod
    engine: redis
    container: stock-selector-prod-01-redis-1
    project: stock-selector-prod-01
    data: /home/ubuntu/databases/kv/stock-selector-prod-01/data
    domain: stock-selector-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: redis, image: "redis:latest", image_id: "sha256:e48e4ac2fa6b1dc2bb9abc9278df84653d3b38d5db82a2d414d3814f296e388e", data: /home/ubuntu/databases/kv/stock-selector-prod-01/data, compose: /home/ubuntu/databases/kv/stock-selector-prod-01/docker-compose.yaml, http_domain: stock-selector-prod-01.kv-na01.storage.evanovation.com}
    target: {engine: redis, image: "redis:7.2.5@sha256:f5ef9e24a9ef3b7cc552ae0cbc3cbade4f2877502683496c5d775605ae071412", data: /home/ubuntu/databases/kv/stock-selector-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/stock-selector-prod-01-kv/password"}
    settings: {}
    http: {enabled: true, port: 13386, domain: stock-selector-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/stock-selector-prod-01-kv/http-token", max_connections: 20}

  - id: test-dev-01
    env: dev
    engine: dragonfly
    container: test-dev-01-redis-1
    project: test-dev-01
    data: /home/ubuntu/databases/kv/test-dev-01/data
    domain: test-dev-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/test-dev-01/data, compose: /home/ubuntu/databases/kv/test-dev-01/docker-compose.yaml, http_domain: test-dev-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/test-dev-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/test-dev-01-kv/password"}
    settings: {threads: 1, maxmemory: 256mb, cache: false}
    http: {enabled: true, port: 13379, domain: test-dev-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/test-dev-01-kv/http-token", max_connections: 20}

  - id: vercount-prod-01
    env: prod
    engine: dragonfly
    container: vercount-prod-01-redis-1
    project: vercount-prod-01
    data: /home/ubuntu/databases/kv/vercount-prod-01/data
    domain: vercount-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1", image_id: "sha256:f99b9720092ba1720df24073c27459482e5f32a0970c6466626d22259b9cb2da", data: /home/ubuntu/databases/kv/vercount-prod-01/data, compose: /home/ubuntu/databases/kv/vercount-prod-01/docker-compose.yaml, http_domain: vercount-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: dragonfly, image: "docker.dragonflydb.io/dragonflydb/dragonfly:v1.34.1@sha256:99eb2dd14ca00b983c302d0a15d15176dccd5a9e85a375bcc5157e1cadd73099", data: /home/ubuntu/databases/kv/vercount-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/vercount-prod-01-kv/password"}
    settings: {threads: 4, maxmemory: 2048mb, cache: false}
    http: {enabled: true, port: 13381, domain: vercount-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/vercount-prod-01-kv/http-token", max_connections: 20}

  - id: xai-server-prod-01
    env: prod
    engine: redis
    container: xai-server-prod-01-redis-1
    project: xai-server-prod-01
    data: /home/ubuntu/databases/kv/xai-server-prod-01/data
    domain: xai-server-prod-01.kv-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: redis, image: "redis:latest", image_id: "sha256:e48e4ac2fa6b1dc2bb9abc9278df84653d3b38d5db82a2d414d3814f296e388e", data: /home/ubuntu/databases/kv/xai-server-prod-01/data, compose: /home/ubuntu/databases/kv/xai-server-prod-01/docker-compose.yaml, http_domain: xai-server-prod-01.kv-montreal-01.storage.evanovation.com}
    target: {engine: redis, image: "redis:7.2.5@sha256:f5ef9e24a9ef3b7cc552ae0cbc3cbade4f2877502683496c5d775605ae071412", data: /home/ubuntu/databases/kv/xai-server-prod-01/data}
    backup: {enabled: true}
    resources: *kv_resources
    secrets: {password: "op://Evanovation/xai-server-prod-01-kv/password"}
    settings: {}
    http: {enabled: true, port: 13387, domain: xai-server-prod-01.kv-montreal-01.storage.evanovation.com, image: "hiett/serverless-redis-http@sha256:5b0bb9239fce53abf87b2018a7a0deb9ec7bd900c5360738fe5fbeeb426f9150", token: "op://Evanovation/xai-server-prod-01-kv/http-token", max_connections: 20}
