instances:
  - id: api-test-01
    env: test
    engine: postgres
    container: api-test-01-postgres-1
    project: api-test-01
    data: /home/ubuntu/databases/postgres/api-test-01/data
    domain: api-test-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/api-test-01/data, compose: /home/ubuntu/databases/postgres/api-test-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/api-test-01/data}
    backup: {enabled: true}
    resources: &postgres_resources {database: unlimited, pgbouncer: unlimited}
    secrets: {password: "op://Evanovation/api-test-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: code-share-prod-01
    env: prod
    engine: postgres
    container: code-share-prod-01-postgres-1
    project: code-share-prod-01
    data: /home/ubuntu/databases/postgres/code-share-prod-01/data
    domain: code-share-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/code-share-prod-01/data, compose: /home/ubuntu/databases/postgres/code-share-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/code-share-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/code-share-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: cs-ai-prod-01
    env: prod
    engine: postgres
    container: cs-ai-prod-01-postgres-1
    project: cs-ai-prod-01
    data: /home/ubuntu/databases/postgres/cs-ai-prod-01/data
    domain: cs-ai-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/cs-ai-prod-01/data, compose: /home/ubuntu/databases/postgres/cs-ai-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/cs-ai-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/cs-ai-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: dialogue-dev-01
    env: dev
    engine: postgres
    container: dialogue-dev-01-postgres-1
    project: dialogue-dev-01
    data: /home/ubuntu/databases/postgres/dialogue-dev-01/data
    domain: dialogue-dev-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/dialogue-dev-01/data, compose: /home/ubuntu/databases/postgres/dialogue-dev-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/dialogue-dev-01/data}
    backup: {enabled: true}
    resources: {database: unlimited}
    secrets: {password: "op://Evanovation/dialogue-dev-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: false, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: gpt-accounts-manager-prod-01
    env: prod
    engine: postgres
    container: gpt-accounts-manager-prod-01-postgres-1
    project: gpt-accounts-manager-prod-01
    data: /home/ubuntu/databases/postgres/gpt-accounts-manager-prod-01/data
    domain: gpt-accounts-manager-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/gpt-accounts-manager-prod-01/data, compose: /home/ubuntu/databases/postgres/gpt-accounts-manager-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/gpt-accounts-manager-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/gpt-accounts-manager-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: gpt-share-prod-01
    env: prod
    engine: postgres
    container: gpt-share-prod-01-postgres-1
    project: gpt-share-prod-01
    data: /home/ubuntu/databases/postgres/gpt-share-prod-01/data
    domain: gpt-share-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/gpt-share-prod-01/data, compose: /home/ubuntu/databases/postgres/gpt-share-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/gpt-share-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/gpt-share-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 2000, pool_size: 30, reserve_size: 10}

  - id: gpt-share-prod-02
    env: prod
    engine: postgres
    container: gpt-share-prod-02-postgres-1
    project: gpt-share-prod-02
    data: /home/ubuntu/databases/postgres/gpt-share-prod-02/data
    domain: gpt-share-prod-02.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/gpt-share-prod-02/data, compose: /home/ubuntu/databases/postgres/gpt-share-prod-02/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/gpt-share-prod-02/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/gpt-share-prod-02-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: gpt-share-prod-03
    env: prod
    engine: postgres
    container: gpt-share-prod-03-postgres-1
    project: gpt-share-prod-03
    data: /home/ubuntu/databases/postgres/gpt-share-prod-03/data
    domain: gpt-share-prod-03.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/gpt-share-prod-03/data, compose: /home/ubuntu/databases/postgres/gpt-share-prod-03/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/gpt-share-prod-03/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/gpt-share-prod-03-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: test-dev-01
    env: dev
    engine: postgres
    container: test-dev-01-postgres-1
    project: test-dev-01
    data: /home/ubuntu/databases/postgres/test-dev-01/data
    domain: test-dev-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/test-dev-01/data, compose: /home/ubuntu/databases/postgres/test-dev-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/test-dev-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/test-dev-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: umami-prod-01
    env: prod
    engine: postgres
    container: umami-prod-01-postgres-1
    project: umami-prod-01
    data: /home/ubuntu/databases/postgres/umami-prod-01/data
    domain: umami-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/umami-prod-01/data, compose: /home/ubuntu/databases/postgres/umami-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/umami-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/umami-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: vercount-prod-01
    env: prod
    engine: postgres
    container: vercount-prod-01-postgres-1
    project: vercount-prod-01
    data: /home/ubuntu/databases/postgres/vercount-prod-01/data
    domain: vercount-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/vercount-prod-01/data, compose: /home/ubuntu/databases/postgres/vercount-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/vercount-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/vercount-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: waline-prod-01
    env: prod
    engine: postgres
    container: waline-prod-01-postgres-1
    project: waline-prod-01
    data: /home/ubuntu/databases/postgres/waline-prod-01/data
    domain: waline-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/waline-prod-01/data, compose: /home/ubuntu/databases/postgres/waline-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/waline-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/waline-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: waline-prod-02
    env: prod
    engine: postgres
    container: waline-prod-02-postgres-1
    project: waline-prod-02
    data: /home/ubuntu/databases/postgres/waline-prod-02/data
    domain: waline-prod-02.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/waline-prod-02/data, compose: /home/ubuntu/databases/postgres/waline-prod-02/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/waline-prod-02/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/waline-prod-02-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}

  - id: whereto-prod-01
    env: prod
    engine: postgres
    container: whereto-prod-01-postgres-1
    project: whereto-prod-01
    data: /home/ubuntu/databases/postgres/whereto-prod-01/data
    domain: whereto-prod-01.postgres-montreal-01.storage.evanovation.com
    durable: true
    current: {engine: postgres, image: "postgres:16", image_id: "sha256:f91377b220f1c6d94a42b63b2b203d558fcd2b45871c5ae4e397c164097cb1a0", data: /home/ubuntu/databases/postgres/whereto-prod-01/data, compose: /home/ubuntu/databases/postgres/whereto-prod-01/docker-compose.yaml}
    target: {engine: postgres, image: "postgres:16@sha256:46aa2ee5d664b275f05d1a963b30fff60fb422b4b594d509765c42db46d48881", data: /home/ubuntu/databases/postgres/whereto-prod-01/data}
    backup: {enabled: true}
    resources: *postgres_resources
    secrets: {password: "op://Evanovation/whereto-prod-01-postgres/password"}
    settings: {user: default, database: postgres, pgbouncer: true, max_clients: 100, pool_size: 20, reserve_size: 5}
