all:
  children:
    test:
      hosts:
        local:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          evdb_become: false
          evdb_root: /tmp/evanovation-db-test/opt
          evdb_config_dir: /tmp/evanovation-db-test/etc
          evdb_secret_dir: /tmp/evanovation-db-test/etc/secrets
          evdb_state_dir: /tmp/evanovation-db-test/state
          evdb_repos:
            postgres: "{{ evdb_state_dir }}/repos/postgres"
            kv: "{{ evdb_state_dir }}/repos/kv"
          evdb_unit_dir: /tmp/evanovation-db-test/systemd
          evdb_user: "{{ lookup('env', 'USER') }}"
          evdb_group: "{{ lookup('env', 'USER') }}"
          evdb_admin_user: "{{ lookup('env', 'USER') }}"
          evdb_admin_group: "{{ lookup('env', 'USER') }}"
          evdb_manage_user: false
          evdb_manage_systemd: false
          evdb_skip_secrets: true
